/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueocs.vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import parqueocs.vista.InicioSesion;

/**
 *
 * @author minio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Sistema de Parqueo - Principal");
    }

    public JButton getBtnEditarVehiculo() {
        return btnEliminarVehiculo;
    }

    public void setBtnEditarVehiculo(JButton btnEditarVehiculo) {
        this.btnEliminarVehiculo = btnEditarVehiculo;
    }

    public JButton getBtnParquear() {
        return btnParquear;
    }

    public void setBtnParquear(JButton btnParquear) {
        this.btnParquear = btnParquear;
    }

    public JButton getBtnRegistrarVehiculo() {
        return btnRegistrarVehiculo;
    }

    public void setBtnRegistrarVehiculo(JButton btnRegistrarVehiculo) {
        this.btnRegistrarVehiculo = btnRegistrarVehiculo;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JLabel getLabelParqueados() {
        return labelParqueados;
    }

    public void setLabelParqueados(JLabel labelParqueados) {
        this.labelParqueados = labelParqueados;
    }

    public JLabel getLabelTitulo1() {
        return labelTitulo1;
    }

    public void setLabelTitulo1(JLabel labelTitulo1) {
        this.labelTitulo1 = labelTitulo1;
    }

    public JList<String> getListParqueados() {
        return listParqueados;
    }

    public void setListParqueados(JList<String> listParqueados) {
        this.listParqueados = listParqueados;
    }

    public JList<String> getListVehiculos() {
        return listVehiculos;
    }

    public void setListVehiculos(JList<String> listVehiculos) {
        this.listVehiculos = listVehiculos;
    }


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelParqueados = new javax.swing.JLabel();
        labelTitulo1 = new javax.swing.JLabel();
        btnRegistrarVehiculo = new javax.swing.JButton();
        btnEliminarVehiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listParqueados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listVehiculos = new javax.swing.JList<>();
        btnParquear = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelParqueados.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        labelParqueados.setText("Parqueados");

        labelTitulo1.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        labelTitulo1.setText("Autos");

        btnRegistrarVehiculo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRegistrarVehiculo.setText("Nuevo Vehiculo");
        btnRegistrarVehiculo.setAlignmentX(0.5F);
        btnRegistrarVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarVehiculo.setMargin(new java.awt.Insets(4, 8, 1, 8));
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });

        btnEliminarVehiculo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnEliminarVehiculo.setText("Eliminar Vehiculo");
        btnEliminarVehiculo.setAlignmentX(0.5F);
        btnEliminarVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarVehiculo.setMargin(new java.awt.Insets(4, 8, 1, 8));
        btnEliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVehiculoActionPerformed(evt);
            }
        });

        listParqueados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listParqueados);

        listVehiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listVehiculos);

        btnParquear.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnParquear.setText("Parquear");
        btnParquear.setAlignmentX(0.5F);
        btnParquear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnParquear.setMargin(new java.awt.Insets(4, 8, 1, 8));
        btnParquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParquearActionPerformed(evt);
            }
        });

        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueocs/resources/actualizar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelParqueados)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrarVehiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarVehiculo)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefrescar))))
                    .addComponent(btnParquear, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(labelTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefrescar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarVehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnParquear)
                .addGap(44, 44, 44)
                .addComponent(labelParqueados)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    private void btnEliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarVehiculoActionPerformed

    private void btnParquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParquearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParquearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminarVehiculo;
    public javax.swing.JButton btnParquear;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelParqueados;
    private javax.swing.JLabel labelTitulo1;
    public javax.swing.JList<String> listParqueados;
    public javax.swing.JList<String> listVehiculos;
    // End of variables declaration//GEN-END:variables
}
