/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueocs.vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import parqueocs.vista.InicioSesion;

/**
 *
 * @author Eddy Mena Lopez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    ColoresInterfaz colores = new ColoresInterfaz();
    TamaniosInterfaz tamanios = new TamaniosInterfaz();
    
    public Principal() {
        setContentPane(new Fondo());
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Sistema de Parqueo - Principal");
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelParqueados = new javax.swing.JLabel();
        labelTitulo1 = new javax.swing.JLabel();
        btnRegistrarVehiculo = new javax.swing.JButton();
        btnEliminarVehiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listParqueados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listVehiculos = new javax.swing.JList<>();
        btnParquear = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnRefrescarParqueados = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labelSaludo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelParqueados.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        labelParqueados.setText("Autos Parqueados");

        labelTitulo1.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        labelTitulo1.setText("Todos los Autos");

        btnRegistrarVehiculo.setBackground(colores.getColorPrimario());
        btnRegistrarVehiculo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRegistrarVehiculo.setForeground(colores.getColorTexto());
        btnRegistrarVehiculo.setText("Nuevo Vehiculo");
        btnRegistrarVehiculo.setAlignmentX(0.5F);
        btnRegistrarVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarVehiculo.setMargin(new java.awt.Insets(4, 8, 1, 8));
        btnRegistrarVehiculo.setPreferredSize(new java.awt.Dimension(110, 30));
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });

        btnEliminarVehiculo.setBackground(colores.getColorPrimario());
        btnEliminarVehiculo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnEliminarVehiculo.setForeground(colores.getColorTexto());
        btnEliminarVehiculo.setText("Eliminar Vehiculo");
        btnEliminarVehiculo.setAlignmentX(0.5F);
        btnEliminarVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarVehiculo.setMargin(new java.awt.Insets(4, 8, 1, 8));
        btnEliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVehiculoActionPerformed(evt);
            }
        });

        listParqueados.setSelectionBackground(colores.getColorSecundario());
        listParqueados.setSelectionForeground(colores.getColorBordes());
        jScrollPane1.setViewportView(listParqueados);

        listVehiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listVehiculos.setSelectionBackground(colores.getColorSecundario());
        listVehiculos.setSelectionForeground(colores.getColorBordes());
        jScrollPane2.setViewportView(listVehiculos);

        btnParquear.setBackground(colores.getColorPrimario());
        btnParquear.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnParquear.setForeground(colores.getColorTexto());
        btnParquear.setText("Parquear");
        btnParquear.setAlignmentX(0.5F);
        btnParquear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnParquear.setMargin(new java.awt.Insets(4, 8, 1, 8));
        btnParquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParquearActionPerformed(evt);
            }
        });

        btnRefrescar.setBackground(colores.getColorPrimario());
        btnRefrescar.setForeground(colores.getColorTexto());
        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueocs/resources/actualizar.png"))); // NOI18N

        btnRefrescarParqueados.setBackground(colores.getColorPrimario());
        btnRefrescarParqueados.setForeground(colores.getColorTexto());
        btnRefrescarParqueados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueocs/resources/actualizar.png"))); // NOI18N

        btnPagar.setBackground(colores.getColorPrimario());
        btnPagar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnPagar.setForeground(colores.getColorTexto());
        btnPagar.setText("Salir y Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(colores.getColorPrimario());
        btnModificar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnModificar.setForeground(colores.getColorTexto());
        btnModificar.setText("Modificar Tiempo");

        btnCerrarSesion.setBackground(colores.getColorPrimario());
        btnCerrarSesion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(colores.getColorTexto());
        btnCerrarSesion.setText("Cerrar Sesion");

        labelSaludo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        labelSaludo.setText("Hola");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelParqueados)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefrescarParqueados))
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSaludo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarVehiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefrescar))
                            .addComponent(jScrollPane2)
                            .addComponent(labelTitulo1)
                            .addComponent(btnParquear, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(labelSaludo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnParquear)
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelParqueados))
                    .addComponent(btnRefrescar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar)
                    .addComponent(btnRefrescarParqueados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPagar)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    private void btnEliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarVehiculoActionPerformed

    private void btnParquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParquearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParquearActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnEliminarVehiculo;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnPagar;
    public javax.swing.JButton btnParquear;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnRefrescarParqueados;
    public javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelParqueados;
    public javax.swing.JLabel labelSaludo;
    private javax.swing.JLabel labelTitulo1;
    public javax.swing.JList<String> listParqueados;
    public javax.swing.JList<String> listVehiculos;
    // End of variables declaration//GEN-END:variables
}
